### ISSUE TITLE
Share Graph does not match calculated graph

### ISSUE THREAD

**Issue by LiminalityCarb** [elxris/Turnip-Calculator#79] opened 2020-04-15 16:36 UTC
Turnip prices of:
Buy: 103
Mon AM: 70
Mon PM: 65
Tue AM: 62
Tue PM: 57
Wed AM: 53
Wed PM: 48
Displays a graph where it looks like the spike would be Friday PM/Saturday AM.
![image](https://user-images.githubusercontent.com/63738980/79363059-63956f80-7f15-11ea-9d6e-2d471eda81b3.png)

However, the share graph is very different:
![image](https://user-images.githubusercontent.com/63738980/79363102-7740d600-7f15-11ea-8fd1-a1b2fabfe922.png)

For some reason it has both the spike occurring Wed PM, and the daily price line is all sorts of wrong.  It should be trending down from day 1, not going up from Tue through Wed, and not missing from Mon PM through Tue PM.

I am assuming something isn't being parsed correctly with the given inputs.

**Comment by LiminalityCarb** [comment] 2020-04-15 16:39
Update - I found what the issue was.  I refreshed the page and it worked, the actual issue is that if I click someone's shared graph, it overwrites what happens when I click the share button with their graph instead even though the "copy this link" works correctly.  So there is still an issue, but its not the issue that I initially described.

**Comment by Eond** [comment] 2020-04-19 17:00
I believe this belongs here, even though it is not precisely the same issue LiminalityCarb explained.

Take a look at this data : [](https://ac-turnip.com/#101-91-88-84-104-160-577-163-119)

The graph and the image (of the graph) are different. Minimum on Wednesday afternoon is higher on the graph, and there is not a predicted spike for _Friday afternoon_ either.

Screenshot : 
![image](https://user-images.githubusercontent.com/86714/79694299-75408500-823d-11ea-8c27-9c38535adaf5.png)

**Comment by Weefz** [comment] 2020-04-20 21:39
Yup, also seeing a different graphic/graph on https://ac-turnip.com/#101--133 
![AcTurnipGraph](https://user-images.githubusercontent.com/28969955/79802428-d8bed580-8357-11ea-82ea-ef726d3e88b6.jpg)

**Comment by elxris** [comment] 2020-04-24 05:59
Please check what version of the tool is in use. 1.9 is the latest.
Duplicate of #89

**Closed by elxris** 2020-04-24 05:59 UTC
