### ISSUE TITLE
Different Results between Desktop and Mobile

### ISSUE THREAD

**Issue by evanjs** [elxris/Turnip-Calculator#90] opened 2020-04-20 20:50 UTC
Current data: https://ac-turnip.com/share?f=90-78-122

Desktop Graph: 

![](https://ac-turnip.com/p-90-78-122.png)

Mobile Graph:

![image](https://user-images.githubusercontent.com/1847524/79798846-8e256500-8327-11ea-90b3-d8fcb4443567.png)

<details>
<summary>Mobile Screenshot (Both graphs)</summary>

![image](https://user-images.githubusercontent.com/1847524/79798854-92518280-8327-11ea-80fc-dcd79f6bde72.png)
</details>

Note: Mobile share graph seems to match desktop graph.

Also, the first image is linked directly from the website (i.e. `https://ac-turnip.com/p-90-78-122.png`) so I would imagine this is what the graph is supposed to look like.

Potentially related to https://github.com/elxris/Turnip-Calculator/issues/89?

___

UPDATE:
Just tried to view that issue and the same thing happens on mobile... so this might simply be a duplicate of #89 or #79.

**Comment by Eond** [comment] 2020-04-21 19:55
Sharing from mobile to desktop seems to not work at all. When opening a link shared from mobile on desktop, the website opens on my data: The shared information is ignored.

When I click the above link ([https://ac-turnip.com/share?f=90-78-122](https://ac-turnip.com/share?f=90-78-122)) nothing happens on the page. The reverse is not true, desktop share links (like mine: [https://ac-turnip.com/#93-126-114-137-138](https://ac-turnip.com/#93-126-114-137-138)) work fine on mobile (they do get converted to the mobile format, though).

Strangely, if you open a mobile share link on desktop, then share again, the share link gets garbled with both share content and shows different data depending on the device used. Mobile devices will show the mobile part of the link, and desktops will show the desktop part. Example: [https://ac-turnip.com/share?f=90-78-122#93-126-114-137-138](https://ac-turnip.com/share?f=90-78-122#93-126-114-137-138)

![image](https://user-images.githubusercontent.com/86714/79907933-6d711400-83e8-11ea-96ce-766b34f9ad72.png)

**Comment by elxris** [comment] 2020-04-22 14:05
Sorry about all the confusion.

I’ve been working hard to improve our sharing feature. And I have released a few different versions. Unfortunately this versions will roll themselves slowly due browsers cache. (To enable offline capability).

Also I have been working on the algorithm, a few changes for narrowing results and heuristics filter are now part of the latest version. 1.9.x. This are published to ac-turnip.com

You will see the version at bottom, please look and see if desktop and mobile versions match. If not try a hard refresh (ctrl shift R) on desktop. On mobile I think you will need to close the browser and open it again. Not sure, every browser works differently.

**Comment by elxris** [comment] 2020-04-22 14:08
> Strangely, if you open a mobile share link on desktop, then share again, the share link gets garbled with both share content and shows different data depending on the device used. Mobile devices will show the mobile part of the link, and desktops will show the desktop part. Example: https://ac-turnip.com/share?f=90-78-122#93-126-114-137-138
> 
> ![image](https://user-images.githubusercontent.com/86714/79907933-6d711400-83e8-11ea-96ce-766b34f9ad72.png)

Oh, this is a bug.

**Comment by elxris** [comment] 2020-04-24 05:57
> > Strangely, if you open a mobile share link on desktop, then share again, the share link gets garbled with both share content and shows different data depending on the device used. Mobile devices will show the mobile part of the link, and desktops will show the desktop part. Example: https://ac-turnip.com/share?f=90-78-122#93-126-114-137-138
> > ![image](https://user-images.githubusercontent.com/86714/79907933-6d711400-83e8-11ea-96ce-766b34f9ad72.png)
> 
> Oh, this is a bug.

I'm unable to reproduce this. I think maybe I fixed somehow in a later deploy. Please open another issue if this behavior continues. The hash part is no longer used.

I will close this as the main issue was because different versions of the tool were used.

**Closed by elxris** 2020-04-24 05:57 UTC
